### PR TITLE
Bug fix in the option parsing for "--json"

### PR DESCRIPTION
**Pull request by sazzer**
Fixed an issue where the option parser would parse a value for "--json" as a boolean True instead of as a path, making it impossible to actually provide a json path to the "yogi loader" command line call.

I found this trying to use Yogi to do builds of a set of Yui3 modules that I want to keep the built modules and loader files distinct from the source tree. This patch makes that work correctly.

### CODE REVIEW

**Comment by davglass** [comment]
`--json` also needs to be a boolean (for other options), this will break that functionality since it will always look for it to have an argument.

**Comment by sazzer** [comment]
Hmm - I did a grep for both "--json" and "options.parsed.json" across the codebase and the only one that came up was the loader one, so I didn't realise there was anything else that used it :(

**Comment by davglass** [comment]
https://github.com/yui/yogi/blob/master/lib/cmds/test.js#L408

**Comment by sazzer** [comment]
Gah - ok, so that's not a unit test then :( Sorry, my bad. I'd seen the
"test" in the file and assumed incorrectly... btw - "yogi help test"
doesn't list --json as an option...

If you're interested, I've just pushed another commit that retains the use
of "--json"/"--no-json" as a boolean whilst allowing it to be used as a
path if any value other than "true" or "false" is passed in. It's not
great, but tests prove that it does work...

**Pull request merged**
