### PR TITLE
Windows 7 issue fix

### PR DESCRIPTION
**Pull request by asotog**
Hi team,

As raised ticket https://github.com/yui/yogi/issues/67 describes, 
there was an issue in Windows 7, the root of the issue was a bug in the complete module https://github.com/hij1nx/complete/commit/eab9c1ff3f0d31905aa235ba9406c72c65225033, 
so the yogi fix consist in an update of the package.json file to use the latest npm build
of the complete module,

Thanks,

### CODE REVIEW

**Comment by davglass** [comment]
Published in `yogi@0.1.4`, thanks!

**Comment by davglass** [comment]
This is now breaking our travis builds :(

https://travis-ci.org/yui/yui3/jobs/6053541

**Comment by asotog** [comment]
Thats weird going to take a look, as you see the only change https://github.com/hij1nx/complete/commits/master was to use process.env.USERPROFILE instead of process.env.HOME when it was undefined, to make it work on windows, maybe something has changed from previous releases from 0.3.1 to 0.4.2 version

**Comment by davglass** [comment]
I filed a PR (hij1nx/complete#19) to add a throw in this case instead of a `process.exit`. Then `yogi` can `try/catch` this the proper way.

I added in a quick hack to `yogi` to skip this when the `TRAVIS` env var is set. Once my PR lands, I'll update to that version and wrap it in a proper `try/catch`.

**Comment by asotog** [comment]
Awesome man, thats cool, thanks

**Pull request merged**
