### PR TITLE
Fixed yogi not working on Windows issue.

### PR DESCRIPTION
**Pull request by benjamind**
Cannot execute batch files with child_process.spawn due to issue in ChildProcess implementation on Windows. See https://github.com/joyent/node/issues/2318 for more discussion.

Easiest workaround this issue is provided by win-spawn package https://npmjs.org/package/win-spawn which fixes this problem by starting the process via a shell.

### CODE REVIEW

**Comment by davglass** [comment]
Make sure that this is used in any other place that it needs to be
instead of just in the build commands.

Thanks!

**Comment by benjamind** [comment]
Ok i'll modify and resubmit.

**Comment by benjamind** [comment]
On further inspection of the source tree and dependencies I'm not entirely sure we'll be completely fixed up with these changes. It appears some of the dependencies also use child_process.spawn, however from looking at them they mostly appear to run full fledged Win32 applications using this method and therefore avoid the bug.

I'll investigate further as I test out Yogi. I suspect there might need to be changes to Shifter too as there's a line in builder.js that appears to run shifter using spawn, but I'm not sure if this ChildProcess bug applies to node installed executables so will address it as it comes up.

**Comment by benjamind** [comment]
I have now successfully built a module with yogi, checked the documentation via 'yogi serve' and submitted a CDN request using yogi. However, it looks like there's a problem in grover since I cannot do 'yogi test' under Windows. The tests in the web interface provided by 'serve' work fine, but they cannot be run on the cli. Will look into this further and possibly submit an issue to the grover project if necessary.

**Comment by davglass** [comment]
Pushed in `yogi@0.0.45`

**Comment by benjamind** [comment]
Good stuff, confirmed all working now (including grover tests) on 0.0.45. Thanks Dav!

**Comment by davglass** [comment]
:metal:

**Pull request closed without merging**
